### ISSUE TITLE
Project Management - Basic Setup

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/healthcare#1]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac You can review the task.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, please put tickets into the Review column, as per instructions.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, correct.
