### ISSUE TITLE
Project Management - Business Case

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/healthcare#2]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I've done it but when I saved it, somehow my text lost all the shape and format. I don't know if it's possible to update pages on wiki? 
About pages I used:
- http://www.projectmanagementdocs.com/project-initiation-templates/business-case.html#axzz58F0Rxh7B
- https://www.business-case-analysis.com/business-case-studies.html#healthcare
- https://resources.workfront.com/project-management-blog/how-to-write-a-business-case-4-steps-to-a-perfect-business-case-template
- https://www.projectmanager.com/blog/project-management/how-to-write-a-business-case and also few examples of Business Casses

**Comment by vasilijajoksimovic** [comment]
@valentinacupac The problem was they flagged my account mistakenly so I couldn't change anything or see anything. I send the report so they corrected all. Now I can change my text on these pages.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, excellent content! 

Please fix the formatting of the headings and sections.
Read about GitHub markdown here https://guides.github.com/features/mastering-markdown/

Can you also try using tables https://help.github.com/articles/organizing-information-with-tables/ for the sections "Business Case Analysis Team" and "Major Project Milestones".

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, also one more point, your roles are both Project Manager and Team Lead.

Then below your name, you can put my name as the Project Advisor (instead of Project Manager). My role will be advising both regarding the project management process (as you wrote) and also advise regarding technical aspects of the project.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac You can review it now. I actually put tables in these chapters but now I understand why all disappeared.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, correct.
