### ISSUE TITLE
Healthcare Project - Initialization

### ISSUE THREAD

**Issue by SavovicGoran** [alptium/healthcare#6]
@vasilijajoksimovic Done.

**Comment by vasilijajoksimovic** [comment]
@SavovicGoran It's ok, I just added milestone.  We'll see about the task for 03.03.2018. After meeting we should define it.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, was @SavovicGoran's task defined? When I look here https://github.com/alptium/healthcare/graphs/contributors it looks like he didn't do anything regarding coding...

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  Yes, it was defined, he just had some problems with his job, he'll try to do it until next meeting...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, thanks. Please for this ticket and for the others, write 1-2 sentences describing the task, so that when I see the tickets, that I can know high-level what each person is working on.

**Comment by vasilijajoksimovic** [comment]
@SavovicGoran  I close this ticket and open another with your task for Monday...
